Repository SFACLOG/sfaclog, pull requests merged in 2024-02, with the labels that each got.

#18 PR: 카드 디자인 시스템 작업
  packages/sfac-design-kit/src/components/Card/DevCard/DevCard.stories.tsx
  packages/sfac-design-kit/src/components/Card/DevCard/index.tsx
  packages/sfac-design-kit/src/components/Card/NotificationCard/NotificationCard.stories.tsx
  packages/sfac-design-kit/src/components/Card/NotificationCard/index.tsx
  packages/sfac-design-kit/src/components/Chip/index.tsx
Labels: design-kit, feat

#21 PR: 디자인 시스템 1차 작업 완료
  packages/sfac-design-kit/src/components/Card/DevCard/DevCard.stories.tsx
  packages/sfac-design-kit/src/components/Card/DevCard/index.tsx
  packages/sfac-design-kit/src/components/Card/NotificationCard/NotificationCard.stories.tsx
  packages/sfac-design-kit/src/components/Card/NotificationCard/index.tsx
  packages/sfac-design-kit/src/components/Card/index.ts
  packages/sfac-design-kit/src/components/Chip/index.tsx
Labels: design-kit, feat

#23 PR: 모달 디자인 시스템 작업
  packages/sfac-design-kit/.storybook/preview-body.html
  packages/sfac-design-kit/src/components/Button/SquareButton.tsx
  packages/sfac-design-kit/src/components/Portal/Modal/Modal.stories.tsx
  packages/sfac-design-kit/src/components/Portal/Modal/index.tsx
Labels: design-kit, feat

#26 PR: 마이페이지 퍼블리싱 작업
  apps/web/next.config.js
  apps/web/public/images/avatar.svg
  apps/web/public/images/gray_box.svg
  apps/web/public/images/left_arrow.svg
  apps/web/public/images/right_arrow.svg
  apps/web/src/api/user.ts
  apps/web/src/app/layout.tsx
  apps/web/src/app/mypage/[userId]/@tabs/default.tsx
  apps/web/src/app/mypage/[userId]/@tabs/log/page.tsx
  apps/web/src/app/mypage/[userId]/@tabs/notification/page.tsx
  apps/web/src/app/mypage/[userId]/layout.tsx
  apps/web/src/app/mypage/[userId]/page.tsx
  apps/web/src/app/mypage/edit/layout.tsx
  apps/web/src/app/mypage/edit/page.tsx
  apps/web/src/app/mypage/policy/layout.tsx
  apps/web/src/app/mypage/policy/page.tsx
  apps/web/src/app/mypage/withdraw/layout.tsx
  apps/web/src/app/mypage/withdraw/page.tsx
  packages/sfac-design-kit/.storybook/preview-body.html
  packages/sfac-design-kit/index.ts
  packages/sfac-design-kit/src/components/Button/RoundButton.tsx
  packages/sfac-design-kit/src/components/Button/SquareButton.tsx
  packages/sfac-design-kit/src/components/Card/DevCard/DevCard.stories.tsx
  packages/sfac-design-kit/src/components/Card/DevCard/index.tsx
  packages/sfac-design-kit/src/components/Card/LargeLogCard/index.tsx
  packages/sfac-design-kit/src/components/Card/NotificationCard/NotificationCard.stories.tsx
  packages/sfac-design-kit/src/components/Card/NotificationCard/index.tsx
  packages/sfac-design-kit/src/components/Card/ProfileCard/index.tsx
  packages/sfac-design-kit/src/components/Card/index.ts
  packages/sfac-design-kit/src/components/Chip/index.tsx
  packages/sfac-design-kit/src/components/Form/Input/index.tsx
  packages/sfac-design-kit/src/components/Form/SelectBox/index.tsx
  packages/sfac-design-kit/src/components/Portal/Modal/Modal.stories.tsx
  packages/sfac-design-kit/src/components/Portal/Modal/index.tsx
  packages/sfac-design-kit/src/components/Portal/index.ts
  packages/sfac-design-kit/src/components/common/ImageWrapper.tsx
  packages/tailwind-config/tailwind.config.ts
Labels: style, sfaclog, feat

#29 Feat/sfaclog/main
  apps/web/.env
  apps/web/next.config.js
  apps/web/package.json
  apps/web/public/images/main/nextButton.svg
  apps/web/public/images/main/prevButton.svg
  apps/web/public/images/serverless-color.svg
  apps/web/public/images/serverless.svg
  apps/web/src/app/main/(components)/FollowSection.tsx
  apps/web/src/app/main/(components)/NewLogSection.tsx
  apps/web/src/app/main/(components)/PopularLogSection.tsx
  apps/web/src/app/main/(components)/RecentNewsSection.tsx
  apps/web/src/app/main/(components)/SectionHeader.tsx
  apps/web/src/app/main/(components)/SectionWrapper.tsx
  apps/web/src/app/main/(components)/SfacProgramCard.tsx
  apps/web/src/app/main/(components)/SfacProgramSection.tsx
  apps/web/src/app/main/page.tsx
  apps/web/src/components/Carousel.tsx
  apps/web/src/components/CarouselArrowButton.tsx
  packages/sfac-design-kit/src/components/Card/DevCard/index.tsx
  packages/sfac-design-kit/src/components/Card/LogCard/index.tsx
  packages/sfac-design-kit/src/components/Card/UserCard/index.tsx
  yarn.lock
Labels: chore, design-kit, style, sfaclog, feat

#35 PR: 프로필 페이지 api 및 기능 작업
  .husky/commit-msg
  apps/web/.env
  apps/web/src/api/index.ts
  apps/web/src/api/post.ts
  apps/web/src/api/user.ts
  apps/web/src/app/Provider.tsx
  apps/web/src/app/hooks/useUserData.ts
  apps/web/src/app/mypage/[userId]/@tabs/log/page.tsx
  apps/web/src/app/profile/[userId]/@tabs/default.tsx
  apps/web/src/app/profile/[userId]/@tabs/log/page.tsx
  apps/web/src/app/profile/[userId]/@tabs/notification/page.tsx
  apps/web/src/app/profile/[userId]/default.tsx
  apps/web/src/app/profile/[userId]/layout.tsx
  apps/web/src/app/profile/[userId]/page.tsx
  apps/web/src/app/profile/edit/layout.tsx
  apps/web/src/app/profile/edit/page.tsx
  apps/web/src/app/profile/policy/layout.tsx
  apps/web/src/app/profile/policy/page.tsx
  apps/web/src/app/profile/withdraw/layout.tsx
  apps/web/src/app/profile/withdraw/page.tsx
  apps/web/src/hooks/usePostData.ts
  apps/web/src/hooks/useUserData.ts
  apps/web/src/types/post.ts
  packages/sfac-design-kit/src/components/Card/LargeLogCard/index.tsx
  packages/sfac-design-kit/src/components/Card/ProfileCard/index.tsx
Labels: sfaclog, feat

#36 PR: 메인 배너 컴포넌트 추가 및 design-kit 아바타 컴포넌트 리팩토링
  apps/web/public/images/main/MainBanner.svg
  apps/web/src/app/main/(components)/MainBanner.tsx
  apps/web/src/app/main/(components)/RecentNewsSection.tsx
  apps/web/src/app/main/page.tsx
  packages/sfac-design-kit/src/components/Avatar/index.tsx
  packages/sfac-design-kit/src/components/Card/DevCard/index.tsx
Labels: design-kit, refactor, sfaclog, feat

#37 PR: 프로필 수정 페이지 api 및 기능 작업
  apps/web/.env
  apps/web/public/images/proposal/opinion.svg
  apps/web/public/images/proposal/project.svg
  apps/web/public/images/proposal/recruit.svg
  apps/web/src/api/user.ts
  apps/web/src/app/profile/[userId]/page.tsx
  apps/web/src/app/profile/edit/page.tsx
  apps/web/src/hooks/useUserData.ts
  apps/web/src/types/user.ts
Labels: sfaclog, feat

#38 PR: main page 로그인 여부에 따른 조건부 렌더링 기능 추가
  apps/web/src/app/Provider.tsx
  apps/web/src/app/login/page.tsx
  apps/web/src/app/login/password/1/page.tsx
  apps/web/src/app/login/password/page.tsx
  apps/web/src/app/main/(components)/FollowSection.tsx
  apps/web/src/app/main/(components)/MainBannerSection.tsx
  apps/web/src/app/main/(components)/MyProfile.tsx
  apps/web/src/app/main/(components)/MySfaclogNotification.tsx
  apps/web/src/app/main/(components)/RecentNewsSection.tsx
  apps/web/src/app/main/page.tsx
  apps/web/src/app/page.tsx
  apps/web/src/app/signup/1/page.tsx
  apps/web/src/app/signup/page.tsx
  apps/web/src/context/UserContext.tsx
  apps/web/utils/convertTimeFormat.ts
  packages/sfac-design-kit/src/components/Button/SquareButton.tsx
Labels: etc, sfaclog, feat

#39 PR: 회원 탈퇴 기능 작업
  apps/web/src/app/profile/withdraw/layout.tsx
  apps/web/src/app/profile/withdraw/page.tsx
Labels: sfaclog, feat

#42 PR: 로그 작성 페이지 추가
  apps/web/src/app/main/(components)/MySfaclogNotification.tsx
  apps/web/src/app/recent-log/write/(components)/CustomToolbarItems.tsx
  apps/web/src/app/recent-log/write/(components)/MarkdownEditor.tsx
  apps/web/src/app/recent-log/write/(components)/toolbar.css
  apps/web/src/app/recent-log/write/page.tsx
  apps/web/src/utils/convertTimeFormat.ts
Labels: etc, feat

#43 PR: 팔로우 기능 api 작업
  apps/web/src/api/follow.ts
  apps/web/src/app/profile/[userId]/layout.tsx
  apps/web/src/app/profile/[userId]/page.tsx
  apps/web/src/components/Modal.tsx
  apps/web/src/hooks/useFollowData.ts
  apps/web/src/hooks/usePostData.ts
  apps/web/src/types/user.ts
  packages/sfac-design-kit/src/components/Card/ProfileCard/index.tsx
  packages/sfac-design-kit/src/components/Portal/Modal/index.tsx
Labels: sfaclog, feat

#44 PR: 공통 레이아웃 작업
  apps/docs/.eslintrc.js
  apps/docs/.gitignore
  apps/docs/README.md
  apps/docs/next-env.d.ts
  apps/docs/next.config.js
  apps/docs/package.json
  apps/docs/postcss.config.js
  apps/docs/public/circles.svg
  apps/docs/public/next.svg
  apps/docs/public/turborepo.svg
  apps/docs/public/vercel.svg
  apps/docs/src/app/favicon.ico
  apps/docs/src/app/globals.css
  apps/docs/src/app/layout.tsx
  apps/docs/src/app/page.tsx
  apps/docs/tailwind.config.ts
  apps/docs/tsconfig.json
  apps/web/public/images/main_logo.svg
  apps/web/public/images/search.svg
  apps/web/public/images/sns/facebook.svg
  apps/web/public/images/sns/github.svg
  apps/web/public/images/sns/instagram.svg
  apps/web/src/app/globals.css
  apps/web/src/app/layout.tsx
  apps/web/src/app/page.tsx
  apps/web/src/app/profile/[userId]/layout.tsx
  apps/web/src/app/profile/[userId]/page.tsx
  apps/web/src/app/profile/edit/page.tsx
  apps/web/src/app/signup/page.tsx
  apps/web/src/app/test/page.tsx
  apps/web/src/components/Header.tsx
  apps/web/src/components/LoginLayout.tsx
  apps/web/src/components/Logo.tsx
  apps/web/src/components/RandomNumber.tsx
  apps/web/src/components/Test.tsx
  apps/web/src/components/layout/Footer.tsx
  apps/web/src/components/layout/Header.tsx
  apps/web/src/components/layout/Navigation.tsx
  apps/web/src/utils/math.ts
  packages/sfac-design-kit/src/App.tsx
  packages/sfac-design-kit/src/main.tsx
Labels: style, sfaclog

#45 PR: 프로필 페이지 유저 flow test
  apps/web/src/app/profile/[userId]/@tabs/bookmark-log/page.tsx
  apps/web/src/app/profile/[userId]/@tabs/log/page.tsx
  apps/web/src/app/profile/[userId]/@tabs/notification/page.tsx
  apps/web/src/app/profile/[userId]/@tabs/recent-view-log/page.tsx
  apps/web/src/app/profile/[userId]/layout.tsx
  apps/web/src/app/profile/[userId]/page.tsx
  apps/web/src/components/layout/Navigation.tsx
Labels: bug, sfaclog, feat

#47 Feat/recent-log
  apps/web/public/images/ic_big_heart.svg
  apps/web/public/images/ic_bookmark.svg
  apps/web/public/images/ic_dot_menu.svg
  apps/web/public/images/ic_plus.svg
  apps/web/public/images/ic_share.svg
  apps/web/public/images/ic_x.svg
  apps/web/public/images/recent-log/success.svg
  apps/web/src/api/postDetail.ts
  apps/web/src/app/recent-log/(components)/AuthorProfile.tsx
  apps/web/src/app/recent-log/(components)/LogHeader.tsx
  apps/web/src/app/recent-log/(components)/LogTag.tsx
  apps/web/src/app/recent-log/(components)/MarkdownViewer.tsx
  apps/web/src/app/recent-log/[id]/page.tsx
  apps/web/src/app/recent-log/upload-success/[id]/page.tsx
  apps/web/src/app/recent-log/write/(components)/LogUploadModal.tsx
  apps/web/src/app/recent-log/write/(components)/MarkdownEditor.tsx
Labels: sfaclog, feat

#50 Feat/recent log
  apps/web/src/app/recent-log/(components)/AuthorProfile.tsx
  apps/web/src/app/recent-log/(components)/LogHeader.tsx
  apps/web/src/app/recent-log/[id]/page.tsx
Labels: sfaclog, feat

#51 Feat/recent log
  apps/web/src/app/recent-log/(components)/AuthorProfile.tsx
  packages/sfac-design-kit/src/components/Card/LargeLogCard/index.tsx
Labels: design-kit, refactor, sfaclog, feat

#54 로그 상세 페이지 내 Navigation, Footer 컴포넌트 적용
  apps/web/src/app/recent-log/[id]/page.tsx
Labels: feat

#55 Chore: package.json 설정 추가
  apps/web/package.json
Labels: chore

#65 PR: 버그 픽스
  apps/web/src/app/profile/edit/page.tsx
  apps/web/src/app/project/(components)/DetailInfo.tsx
  apps/web/src/app/recent-log/(components)/LogHeader.tsx
  packages/sfac-design-kit/src/components/Card/LargeLogCard/index.tsx
Labels: bug, sfaclog

#66 Feat/recent log
  apps/web/src/api/post.ts
  apps/web/src/api/tag.ts
  apps/web/src/app/main/(components)/MainBannerSection.tsx
  apps/web/src/app/main/(components)/NewLogSection.tsx
  apps/web/src/app/recent-log/(components)/LogTag.tsx
  apps/web/src/app/recent-log/(components)/RecentLogTagSection.tsx
  apps/web/src/app/recent-log/page.tsx
  apps/web/src/components/layout/Navigation.tsx
  packages/sfac-design-kit/src/components/Card/LogCard/index.tsx
  packages/sfac-design-kit/src/components/Form/SelectBox/index.tsx
Labels: design-kit, refactor, style, sfaclog, feat
